env:
  global:
    - CC_TEST_REPORTER_ID=ABC

language: python
python: 3.8

install: make

before_install:
  - pip install poetry
  - pip install flake8

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make run_test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT